### ISSUE TITLE
Bad handsake at blade init

### ISSUE THREAD

**Issue by Lajule** [signalwire/signalwire-golang#91]
Hi,

I'm getting following error when using the library: 

DEBUG: 2021/05/04 08:47:20 client.go:108: cannot init Blade: websocket: bad handshake
ERROR: 2021/05/04 08:47:20 consumer.go:153: Cannot setup Blade: websocket: bad handshake

i'm using :
go 1.16

**Comment by dragos-oancea** [comment]
what if you try an example, like this:  RelayExamples/Inbound# ./Inbound -d -p your-project-id -t your-token-id . 

works with go version go1.12.8 linux/amd64 .

Can you show some code ?

**Comment by Lajule** [comment]
Ok it works with the exemple
